### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by tankerkiller125** [b1naryth1ef/dscord#1]
This Lib looks (and even works) great. The only problem with it is that it lacks proper documentation. Is there a plan to document it in the future?

**Comment by b1naryth1ef** [comment]
Yep I agree, docs would be nice. I haven't really experimented with how to auto-generated docs so there is generally a lack of anything in the actual code. I'll investigate how most people do it and try to throw something together.

**Comment by ccubed** [comment]
https://dlang.org/spec/ddoc.html

Suggestion: doxygen

**Comment by b1naryth1ef** [comment]
I'd like to avoid doxygen if possible, smells like Java and doesn't provide a good enough interface for the cost of setup.

I messed around a little bit with ddox (seemingly the standard around D folk) and haven't managed to actually get it working (just generates empty docs right now). I'll plan on using the ddoc format moving forward, and figuring out the generation part when the API is more stable.

**Comment by b1naryth1ef** [comment]
Docs are building with ddox, and up at http://dscord.hydr0.com/. Will work on actually fleshing them out now.

**Comment by b1naryth1ef** [comment]
Documentation is now fairly easy to build, and I've also covered most of the important spots in the codebase. Further docs will be written as I move forth with other features, so I'm going to close this issue as completed.
